services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo-app
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
